version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /app
      - /app/node_modules
  api:
    build:
      context: .
      args:
        - BUILD_ENV=Development
    command: air
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: .
        target: /go/src/github.com/Bastorx/test_lbc
      - /client/
    environment:
      - ENV=Development
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=test_lbc_user
      - DB_PWD=test_lbc_pwd
      - DB_DATABASE=test_lbc
    links:
      - "db:database"
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test_lbc_user
      MYSQL_PASSWORD: test_lbc_pwd
      MYSQL_DATABASE: test_lbc
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: